[workspace]
resolver = "2"

members = [
    "rust/helloworld",
    "rust/memtest",
    "rust/exception",
    "rust/display",
    "rust/fs/shell",
    "rust/net/echoserver",
    "rust/net/httpclient",
    "rust/net/httpserver",
    "rust/net/udpserver",
    "rust/net/bwbench",
    "rust/task/parallel",
    "rust/task/sleep",
    "rust/task/yield",
    "rust/task/priority",
    "rust/task/tls",
    "rust/task/irq",
    "rust/task/affinity",
    "rust/task/wait_queue",
]
exclude = [".arceos"]

[workspace.dependencies]
axstd = { git = "https://github.com/reL4team2/arceos.git", rev = "165732c" }
axplat-aarch64-sel4 = { git = "https://github.com/reL4team2/arceos.git", rev = "165732c" }

[patch.crates-io]
kernel_guard = { git = "https://github.com/croakexciting/kernel_guard.git", rev = "f0c503d" }
axcpu = { git = "https://github.com/croakexciting/axcpu.git", rev = "d40cb74" }
percpu = { git = "https://github.com/croakexciting/percpu.git", rev = "8d83e54" }
percpu_macros = { git = "https://github.com/croakexciting/percpu.git", rev = "8d83e54" }

[patch."https://github.com/seL4/rust-sel4"]
sel4 = { git = "https://github.com/yfblock/rust-sel4", rev = "1280281" }

[profile.release]
lto = true